DROP TABLE bilet CASCADE CONSTRAINTS;
DROP TABLE film CASCADE CONSTRAINTS;
DROP TABLE klient CASCADE CONSTRAINTS;
DROP TABLE miejsce CASCADE CONSTRAINTS;
DROP TABLE miejscenaseansie CASCADE CONSTRAINTS;
DROP TABLE paragon CASCADE CONSTRAINTS;
DROP TABLE pracownik CASCADE CONSTRAINTS;
DROP TABLE produkt CASCADE CONSTRAINTS;
DROP TABLE produktnaparagonie CASCADE CONSTRAINTS;
DROP TABLE rezerwacja CASCADE CONSTRAINTS;
DROP TABLE rodzajbiletu CASCADE CONSTRAINTS;
DROP TABLE sala CASCADE CONSTRAINTS;
DROP TABLE seans CASCADE CONSTRAINTS;

DROP SEQUENCE bilet_id_seq;