DROP TABLE bilety CASCADE CONSTRAINTS;
DROP TABLE filmy CASCADE CONSTRAINTS;
DROP TABLE klienci CASCADE CONSTRAINTS;
DROP TABLE miejsca CASCADE CONSTRAINTS;
DROP TABLE miejscanaseansie CASCADE CONSTRAINTS;
DROP TABLE paragony CASCADE CONSTRAINTS;
DROP TABLE pracownicy CASCADE CONSTRAINTS;
DROP TABLE produkty CASCADE CONSTRAINTS;
DROP TABLE produktynaparagonie CASCADE CONSTRAINTS;
DROP TABLE rezerwacje CASCADE CONSTRAINTS;
DROP TABLE rodzajebiletow CASCADE CONSTRAINTS;
DROP TABLE sale CASCADE CONSTRAINTS;
DROP TABLE seanse CASCADE CONSTRAINTS;

DROP SEQUENCE bilet_id_seq;
DROP FUNCTION liczba_miejsc_w_sali;